name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy
# validation, and allow manual testing through the repository's "Actions" tab.
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

# Set the permissions to the lowest permissions possible needed for your jobs.
# Copilot will be given its own token for its operations.
permissions:
  # If you want to clone the repository as part of your setup steps, for example
  # to install dependencies, you'll need the `contents: read` permission. If you
  # don't clone the repository in your setup steps, Copilot will do this for you
  # automatically after the steps complete.
  contents: read

jobs:
  # The job MUST be called `copilot-setup-steps` to get picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest
    # container:
    #   image: ghcr.io/devtemplates/nix-devcontainer:1.0.1-ubuntu-22.04
    #   options: --user runner

    # You can define any steps you want, and they will run before the agent starts.
    # If you do not check out your code, Copilot will do this for you.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Install dependencies
        run: nix develop --command pnpm install
