name: Daily Documentation Review

on:
  push:
    branches:
      - jarid/fix-documentation-review-workflow

jobs:
  review-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Verify GH authentication
        run: gh auth status
        env:
          GH_TOKEN: ${{ secrets.GH_CREATE_TASK_TOKEN }}
      - name: Create Copilot Review Issue
        run: |
          gh issue create \
            --repo "${{ github.repository }}" \
            --title "Review documentation accuracy" \
            --body "Please review .github/copilot-instructions.md for accuracy against the current repository state. Check if version references, package counts, and command examples are correct. Create a PR if any updates are needed." \
            --assignee "@copilot"
        env:
          GH_TOKEN: ${{ secrets.GH_CREATE_TASK_TOKEN }}
