name: Daily Documentation Review

on:
  push:
    branches:
      - jarid/fix-documentation-review-workflow

jobs:
  review-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Verify GH authentication
        run: gh auth status
        env:
          GH_TOKEN: ${{ secrets.GH_CREATE_TASK_TOKEN }}
      - name: Trigger Copilot Agent
        run: |
          gh agent-task create \
            "Review .github/copilot-instructions.md for accuracy against current repository state. Check if version references, package counts, and command examples are correct. Create a PR if any updates are needed."
        env:
          GH_TOKEN: ${{ secrets.GH_CREATE_TASK_TOKEN }}
